### ISSUE TITLE
Return to default icon if there's no vscode.ico?

### ISSUE THREAD

**Issue by Gama11** [krizzdewizz/vscode-icon-rotation#1]
It seems like opening a VSCode instance through `codee` will use whatever the icon of the last project was if the newly opened project doesn't have its own icon file.

Could it instead just return to the default (blue) VSCode icon?

**Comment by krizzdewizz** [comment]
Hi, thanks for using icon-rotation! Yes. I'll take a look at it.

**Comment by Gama11** [comment]
Thanks for making it! I think it's a great idea, I always have trouble telling my myriad VSCode windows apart in the task bar (albeit a bit invasive, with you needing to run a wrapper application, but I get that that is necessary).

**Comment by krizzdewizz** [comment]
The new version fixes the bug. Thanks for trying it out.

**Comment by Gama11** [comment]
Can confirm, working as expected now. 👍
